/****************************************************************
	Copyright(C), 1999-2004 Raisecom, Inc.
	filename: ibc.c，板间协议处理函数
	Author	: qiaoqiangguo
	version	: 1.0
	date	: 2008/6/21
	Others	:
        THIS DOCUMENT IS GENERATED BY TORNADO TOOLS refgen.exe
        EXAMPLE:
        ->torVars.bat
        ->refgen -mg -out doc ibc.c
        ->cd doc
        ->htmllink
*****************************************************************/
#include "pocket_hub_config.h"

#ifdef INCLUDE_IBC

#include "string.h"
#include "type_common.h"
#include "macro_common.h"
#include "dev_common.h"
#include "uart_common.h"
//#include "uart.h"

//#include "uart1.h"

//#include "uart2.h"

//#include "uart3.h"

//#include "dev_common.h"
#include "ibc.h"
#ifdef INCLUDE_IBC_RC006
#include "ibc_rc006.h"
#endif
#ifdef INCLUDE_IBC_RC002
#include "ibc_rc002.h"
#endif
#ifdef INCLUDE_OPTTYPE
#include "ibc_opttype.h"
#endif
//xxx_msg_send g_rc7017_msg_send = NULL;
/********************************************************************************
*ibc_msg_rcv --协议接收报文处理函数
*Input:
*	arg			--自定义参数
*	prt			--协议类型
*	pbuf		--接收到的报文头指针	
*	len			--接收的报文长度
*Output:
*	None
*Return:
*	OK			--表示执行成功
*	ERROR		--表示执行错误
*/
STATUS ibc_msg_rcv(OTP_VOID *arg, uart_protocol_type prt,OTP_UINT8 *pbuf, OTP_UINT16 len,OTP_UINT8 version)
{
	switch(prt)
	{
		case UART_PRTTYPE_006:		
#ifdef INCLUDE_IBC_RC006
		/*lint -save -e611*/
			return ibc_msg_rcv_rc006(arg, pbuf, len);
		/*lint -restore*/
#else
			break;
#endif
		case UART_PRTTYPE_004:
			break;
		case UART_PRTTYPE_002:
#ifdef INCLUDE_IBC_RC002
		/*lint -save -e611*/
			return ibc_msg_rcv_rc002(arg, pbuf, len,(rc002_version_type)version);
		/*lint -restore*/
#else
			NO_USE(version);
			break;
#endif
		case UART_PRTTYPE_CONSOLE:
			break;
		case UART_PRTTYPE_INVALID:
			break;
		case UART_PRTTYPE_OPTTYPE:
			break;
		default:
			break;
	}

	return ERROR;
}

/*****************************************************************************
*ibc_init_all		ibc初始化函数
*Input:
*     protocol  -- ibc使用的协议类型
*	uartid	--ibc使用的串口编号，0,1,2；
**Output:
*	None
*Return:
*	OK			--表示执行成功
*	ERROR		--表示执行错误
*/
STATUS ibc_init_all(uart_protocol_type protocol, OTP_UINT8 uartid)
{
	if(protocol == UART_PRTTYPE_002)
	{
#ifdef INCLUDE_IBC_RC002	
		ibc_rc002_init();

		if(uartid == UART1_ID)
		{
#ifdef INCLUDE_OPTTYPE
			if(uart1_rs232_init(UART_PRTTYPE_002, ibc_msg_rcv,ibc_opttype_rcv) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}			
			ibc_opttype_init();
#else
			if(uart1_rs232_init(UART_PRTTYPE_002, ibc_msg_rcv,NULL) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}
#endif

		}
		else if(uartid == UART2_ID)
		{
			if(uart2_rs232_init(UART_PRTTYPE_002, ibc_msg_rcv,NULL) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}
		}	
		else if(uartid == UART3_ID)
		{
			if(uart3_rs232_init(UART_PRTTYPE_002, ibc_msg_rcv,NULL) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}
		}
#endif
	}
	else if(protocol == UART_PRTTYPE_006)
	{
#ifdef INCLUDE_IBC_RC006	
		ibc_rc006_init();

		if(uartid == UART1_ID)
		{
#ifdef INCLUDE_OPTTYPE
			if(uart1_rs232_init(UART_PRTTYPE_006, ibc_msg_rcv, ibc_opttype_rcv) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}
			ibc_opttype_init();
#else
			if(uart1_rs232_init(UART_PRTTYPE_006, ibc_msg_rcv,NULL) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}
#endif
		}
		else if(uartid == UART2_ID)
		{
#ifdef INCLUDE_UART2 
			if(uart2_rs232_init(UART_PRTTYPE_006, ibc_msg_rcv,NULL) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}	
#endif
		}
		else if(uartid == UART3_ID)
		{
#ifdef INCLUDE_UART3
			if(uart3_rs232_init(UART_PRTTYPE_006, ibc_msg_rcv,NULL) != OK)
			{
				MCU_EXC_ERROR;
				return ERROR;
			}
#endif
		}
#endif
	}

	return OK;
}


#endif

