
/* dev_common.h -- 设备管理公共结构定义 Id: dev_common.h,v 1.2 2006/03/14 06:14:49 zhangrongtao Exp $ */

/********************************************************
    Copyright(C), 1999-2004 Raisecom, Inc. 
    filename:      //文件名
    Author： XXX      version:2004/12/20      //初始作者和版本时间
    Others: 
        THIS DOCUMENT IS GENERATED BY TORNADO TOOLS refgen.exe.
        EXAMPLE:
        ->torVars.bat
        ->refgen -mg -out doc driver.c
        ->cd doc 
        ->htmllink
***********************************************************/
/*  
DESCRIPTION  
        设备管理公共结构定义


SEE ALSO
       
*/


#ifndef _DEV_COMMON_H
#define _DEV_COMMON_H

/*远端设备扩展使用的定义*/
typedef union rdevextend{
		OTP_UINT8 reserve;		/*原始定义，保留0*/
		/*保留字节按位域扩展使用*/
		struct{
#ifdef OTP_LITTLE_ENDIAN
		OTP_UINT8	extend:7;	/*bit0-6 保留，0*/
		OTP_UINT8	proType:1;	/*bit7: 表示协议类型
								  1 006协议，表示以净核的方式传输远端设备信息
								  0 004协议，表示保留004协议帧头的方式传输远端设备信息*/
#else
		OTP_UINT8	proType:1;	/*bit7: 表示协议类型
								  1 006协议，表示以净核的方式传输远端设备信息
								  0 004协议，表示保留004协议帧头的方式传输远端设备信息*/
		OTP_UINT8	extend:7;	/*bit6-0 保留，0*/
#endif
		}OTP_PACK_ALIGN(1)r;
}OTP_PACK_ALIGN(1)RDEVEXTEND;					


/*远端设备标识的每跳标识*/
typedef struct rdev_rid_item
{
	OTP_UINT16	devt;			/*设备类型，为dev_type枚举值*/
	RDEVEXTEND 	devext;			/*设备扩展使用*/
	OTP_UINT8	devid;			/*设备ID，局部意义*/
}OTP_PACK_ALIGN(1)rdev_rid_item;/*定义为紧缩的，方便板间通信结构定义*/

#define rdevProType			devext.r.proType
#define rdevExtend 			devext.r.extend
#define rdevReserve			devext.reserve

/*远端设备标识*/
#define RDEV_MAX_RID_NUM	4	/*最大允许的设备标识项数目*/
typedef struct rdev_rid
{
	OTP_UINT8		hop;						/*跳数，0表示非远端设备*/
	rdev_rid_item 	items[RDEV_MAX_RID_NUM];	/*设备标识项数组*/
}OTP_PACK_ALIGN(1)rdev_rid;/*定义为紧缩的，方便板间通信结构定义*/


/*统一的设备标识，可以标识局端单盘和远端设备*/
typedef struct rdev_uniid
{
	OTP_UINT8	slot;	/*设备所在槽位号，如果远端设备标识的跳数为0，就为局端单盘*/
	rdev_rid 	rdid;	/*远端设备标识*/
}/*OTP_PACK_ALIGN(1)*/rdev_uniid;	/*定义为紧缩的，方便板间通信结构定义*/

/*获取远端模块支持的协议类型*/
#define RDEV_PROTYPE(puniid)	((puniid)->rdid.items[(puniid)->rdid.hop-1].rdevProType)


#endif


